[package]
name = "varlen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
varlen_macro = { version = "0.1", path = "../varlen_macro" }

[features]
example_generated = []