[package]
name = "varlen_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
varlen = { version = "0.1", path = "../varlen", features = ["macro"] }

[dev-dependencies]
trybuild = "1.0.54"